#ifndef __IPCAM_CUSTOM_CONFIG__
#define __IPCAM_CUSTOM_CONFIG__
#define IPCAM_CONFIG_IP_CAM_VER_1
#define CONFIG_DEFAULT_ESSID "ROVIO_WOWWEE"
#define CONFIG_DEFAULT_WIFI_AD_HOC 1
#define CONFIG_DEFAULT_MAC {0x00, 0x01, 0x03, 0x20, 0x70, 0x0a}
#define CONFIG_DEFAULT_IP "192.168.10.18"
#define CONFIG_DEFAULT_NETMASK "255.255.255.0"
#define CONFIG_DEFAULT_GATEWAY "192.168.10.1"
#define CONFIG_DEFAULT_IP_METHOD IP_ASSIGNMENT_MANUALLY
#define CONFIG_SENSOR SENSOR_OV7670
#define CONFIG_AUDIO_WM8978_NO_GPIO
#define CONFIG_SDIO_BIT 4
#define CONFIG_MEMORY_SIZE 8
#define CONFIG_USE_UART_MSG 0
#define CONFIG_LOGIN_PROMPT_ADMIN "Administrator for Rovio"
#define CONFIG_LOGIN_PROMPT_USER "Rovio"
#endif
