#ifndef CYGONCE_PKGCONF_HAL_ARM_W99702_H
#define CYGONCE_PKGCONF_HAL_ARM_W99702_H
/*
 * File <pkgconf/hal_arm_w99702.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */
#include "../../../custom_config.h"

#define HAL_PLATFORM_CPU    "ARM 946E"
#define HAL_PLATFORM_BOARD  "Winbond w99702"
#define HAL_PLATFORM_EXTRA  ""

#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS 2
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS_2

#if defined IPCAM_CONFIG_IP_CAM_VER_0 \
	|| defined IPCAM_CONFIG_IP_CAM_VER_1 \
	|| defined IPCAM_CONFIG_IP_CAM_VER_2 \
	|| defined IPCAM_CONFIG_IP_CAM_VER_3
//using uart 0 act as diag_printf
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_DEFAULT 0
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_DEFAULT_0
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL 0
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_0
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL 0
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_0
#elif defined IPCAM_CONFIG_MP4_EVB_VER_0 || defined IPCAM_CONFIG_MP4_EVB_VER_1
//using uart 1 act as diag_printf
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS 2
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS_2
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_DEFAULT 1
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_DEFAULT_1
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL 1
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_1
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL 1
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_1
#else
#	error "No hardware config defined!"
#endif
#define CYGNUM_HAL_VIRTUAL_VECTOR_CHANNELS_DEFAULT_BAUD 115200
#define CYGNUM_HAL_VIRTUAL_VECTOR_CHANNELS_DEFAULT_BAUD_115200
#define CYGNUM_HAL_RTC_CONSTANTS 1
#define CYGNUM_HAL_RTC_NUMERATOR 1000000000
#define CYGNUM_HAL_RTC_NUMERATOR_1000000000
#define CYGNUM_HAL_RTC_DENOMINATOR 100
#define CYGNUM_HAL_RTC_DENOMINATOR_100
#define CYGNUM_HAL_RTC_PERIOD 120000
#define CYGNUM_HAL_RTC_PERIOD_120000
#define CYGBLD_GLOBAL_OPTIONS 1

#endif
