#ifndef CYGONCE_PKGCONF_HAL_ARM_W90N740_H
#define CYGONCE_PKGCONF_HAL_ARM_W90N740_H
/*
 * File <pkgconf/hal_arm_w90n740.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */


#define HAL_PLATFORM_CPU    "ARM 7TDMI"
#define HAL_PLATFORM_BOARD  "Winbond w90n740"
#define HAL_PLATFORM_EXTRA  ""

#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS 1
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS_1
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_DEFAULT 0
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_DEFAULT_0
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL 0
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_0
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL 0
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_0
#define CYGNUM_HAL_VIRTUAL_VECTOR_CHANNELS_DEFAULT_BAUD 115200
#define CYGNUM_HAL_VIRTUAL_VECTOR_CHANNELS_DEFAULT_BAUD_115200
#define CYGNUM_HAL_RTC_CONSTANTS 1
#define CYGNUM_HAL_RTC_NUMERATOR 1000000000
#define CYGNUM_HAL_RTC_NUMERATOR_1000000000
#define CYGNUM_HAL_RTC_DENOMINATOR 100
#define CYGNUM_HAL_RTC_DENOMINATOR_100
#define CYGNUM_HAL_RTC_PERIOD 150000
#define CYGNUM_HAL_RTC_PERIOD_150000
#define CYGBLD_GLOBAL_OPTIONS 1

#endif
