#ifndef CYGONCE_PKGCONF_IO_SERIAL_H
#define CYGONCE_PKGCONF_IO_SERIAL_H
/*
 * File <pkgconf/io_serial.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

/***** proc output start *****/
#include "pkgconf/system.h"
#ifdef CYGDAT_IO_SERIAL_DEVICE_HEADER
# include CYGDAT_IO_SERIAL_DEVICE_HEADER
#endif 
/****** proc output end ******/
#define CYGOPT_IO_SERIAL_SUPPORT_NONBLOCKING 1
#define CYGINT_IO_SERIAL_BLOCK_TRANSFER 1
#define CYGINT_IO_SERIAL_BLOCK_TRANSFER_1
#define CYGINT_IO_SERIAL_LINE_STATUS_HW 0
#define CYGINT_IO_SERIAL_LINE_STATUS_HW_0
#define CYGPKG_IO_SERIAL_TTY 1
#define CYGPKG_IO_SERIAL_HALDIAG 1
#define CYGDAT_IO_SERIAL_TTY_CONSOLE "/dev/ttydiag"
#define CYGPKG_IO_SERIAL_TTY_TTYDIAG 1
#define CYGPKG_IO_SERIAL_TERMIOS 1
#define CYGINT_IO_SERIAL_TERMIOS_TERMIOS_TTY 1
#define CYGINT_IO_SERIAL_TERMIOS_TERMIOS_TTY_1
#define CYGBLD_IO_SERIAL_TERMIOS_TERMIOS_TTY 1
#define CYGPKG_IO_SERIAL_TERMIOS_TERMIOS0 1
#define CYGDAT_IO_SERIAL_TERMIOS_TERMIOS0_DEV "/dev/ser0"
#define CYGPKG_IO_SERIAL_TERMIOS_TERMIOS1 1
#define CYGDAT_IO_SERIAL_TERMIOS_TERMIOS1_DEV "/dev/ser1"
#define CYGSEM_IO_SERIAL_TERMIOS_USE_SIGNALS 1
#define CYGPKG_IO_SERIAL_DEVICES 1
#define CYGPKG_IO_SERIAL_OPTIONS 1
#define CYGPKG_IO_SERIAL_SELECT_SUPPORT 1
#define CYGINT_IO_SERIAL_TEST_SKIP_9600 0
#define CYGINT_IO_SERIAL_TEST_SKIP_9600_0
#define CYGINT_IO_SERIAL_TEST_SKIP_14400 0
#define CYGINT_IO_SERIAL_TEST_SKIP_14400_0
#define CYGINT_IO_SERIAL_TEST_SKIP_19200 0
#define CYGINT_IO_SERIAL_TEST_SKIP_19200_0
#define CYGINT_IO_SERIAL_TEST_SKIP_38400 0
#define CYGINT_IO_SERIAL_TEST_SKIP_38400_0
#define CYGINT_IO_SERIAL_TEST_SKIP_57600 0
#define CYGINT_IO_SERIAL_TEST_SKIP_57600_0
#define CYGINT_IO_SERIAL_TEST_SKIP_115200 1
#define CYGINT_IO_SERIAL_TEST_SKIP_115200_1
#define CYGINT_IO_SERIAL_TEST_SKIP_PARITY_EVEN 0
#define CYGINT_IO_SERIAL_TEST_SKIP_PARITY_EVEN_0
#define CYGINT_IO_SERIAL_TEST_SKIP_PARITY_ODD 0
#define CYGINT_IO_SERIAL_TEST_SKIP_PARITY_ODD_0
#define CYGINT_IO_SERIAL_TEST_SKIP_STOP_2 0
#define CYGINT_IO_SERIAL_TEST_SKIP_STOP_2_0

#endif
