#ifndef CYGONCE_PKGCONF_ISOINFRA_H
#define CYGONCE_PKGCONF_ISOINFRA_H
/*
 * File <pkgconf/isoinfra.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGINT_ISO_MAIN_STARTUP 1
#define CYGINT_ISO_MAIN_STARTUP_1
#define CYGINT_ISO_ENVIRON 1
#define CYGINT_ISO_ENVIRON_1
#define CYGINT_ISO_CTYPE 1
#define CYGINT_ISO_CTYPE_1
//#define CYGBLD_ISO_CTYPE_HEADER "cyg/libc/i18n/ctype.inl"
#define CYGINT_ISO_ERRNO_CODES 1
#define CYGINT_ISO_ERRNO_CODES_1
#define CYGBLD_ISO_ERRNO_CODES_HEADER "cyg/error/codes.h"
#define CYGINT_ISO_ERRNO 1
#define CYGINT_ISO_ERRNO_1
#define CYGBLD_ISO_ERRNO_HEADER "cyg/error/errno.h"
#define CYGINT_ISO_LOCALE 1
#define CYGINT_ISO_LOCALE_1
#define CYGINT_ISO_STDIO_FILETYPES 1
#define CYGINT_ISO_STDIO_FILETYPES_1
#define CYGBLD_ISO_STDIO_FILETYPES_HEADER "cyg/libc/stdio/stdio.h"
#define CYGINT_ISO_STDIO_STREAMS 1
#define CYGINT_ISO_STDIO_STREAMS_1
#define CYGBLD_ISO_STDIO_STREAMS_HEADER "cyg/libc/stdio/stdio.h"
#define CYGINT_ISO_STDIO_FILEACCESS 1
#define CYGINT_ISO_STDIO_FILEACCESS_1
#define CYGBLD_ISO_STDIO_FILEACCESS_HEADER "cyg/libc/stdio/stdio.h"
#define CYGINT_ISO_STDIO_FORMATTED_IO 1
#define CYGINT_ISO_STDIO_FORMATTED_IO_1
#define CYGBLD_ISO_STDIO_FORMATTED_IO_HEADER "cyg/libc/stdio/stdio.h"
#define CYGINT_ISO_STDIO_CHAR_IO 1
#define CYGINT_ISO_STDIO_CHAR_IO_1
#define CYGBLD_ISO_STDIO_CHAR_IO_HEADER "cyg/libc/stdio/stdio.h"
#define CYGINT_ISO_STDIO_DIRECT_IO 1
#define CYGINT_ISO_STDIO_DIRECT_IO_1
#define CYGBLD_ISO_STDIO_DIRECT_IO_HEADER "cyg/libc/stdio/stdio.h"
#define CYGINT_ISO_STDIO_ERROR 1
#define CYGINT_ISO_STDIO_ERROR_1
#define CYGBLD_ISO_STDIO_ERROR_HEADER "cyg/libc/stdio/stdio.h"
#define CYGINT_ISO_STDIO_POSIX_FDFUNCS 1
#define CYGINT_ISO_STDIO_POSIX_FDFUNCS_1
#define CYGINT_ISO_STDLIB_STRCONV 1
#define CYGINT_ISO_STDLIB_STRCONV_1
#define CYGBLD_ISO_STDLIB_STRCONV_HEADER "cyg/libc/stdlib/atox.inl"
#define CYGINT_ISO_STDLIB_STRCONV_FLOAT 1
#define CYGINT_ISO_STDLIB_STRCONV_FLOAT_1
#define CYGINT_ISO_RAND 1
#define CYGINT_ISO_RAND_1
#define CYGINT_ISO_MALLOC 1
#define CYGINT_ISO_MALLOC_1
#define CYGINT_ISO_MALLINFO 1
#define CYGINT_ISO_MALLINFO_1
#define CYGINT_ISO_EXIT 1
#define CYGINT_ISO_EXIT_1
#define CYGINT_ISO_STDLIB_ENVIRON 1
#define CYGINT_ISO_STDLIB_ENVIRON_1
#define CYGINT_ISO_STDLIB_SYSTEM 1
#define CYGINT_ISO_STDLIB_SYSTEM_1
#define CYGINT_ISO_BSEARCH 1
#define CYGINT_ISO_BSEARCH_1
#define CYGINT_ISO_QSORT 1
#define CYGINT_ISO_QSORT_1
#define CYGINT_ISO_ABS 1
#define CYGINT_ISO_ABS_1
#define CYGBLD_ISO_STDLIB_ABS_HEADER "cyg/libc/stdlib/abs.inl"
#define CYGINT_ISO_DIV 1
#define CYGINT_ISO_DIV_1
#define CYGBLD_ISO_STDLIB_DIV_HEADER "cyg/libc/stdlib/div.inl"
#define CYGINT_ISO_STDLIB_MULTIBYTE 1
#define CYGINT_ISO_STDLIB_MULTIBYTE_1
#define CYGINT_ISO_STRERROR 1
#define CYGINT_ISO_STRERROR_1
#define CYGBLD_ISO_STRERROR_HEADER "cyg/error/strerror.h"
#define CYGINT_ISO_STRTOK_R 1
#define CYGINT_ISO_STRTOK_R_1
#define CYGBLD_ISO_STRTOK_R_HEADER "cyg/libc/string/string.h"
#define CYGINT_ISO_STRING_LOCALE_FUNCS 1
#define CYGINT_ISO_STRING_LOCALE_FUNCS_1
#define CYGBLD_ISO_STRING_LOCALE_FUNCS_HEADER "cyg/libc/string/string.h"
#define CYGINT_ISO_STRING_BSD_FUNCS 1
#define CYGINT_ISO_STRING_BSD_FUNCS_1
#define CYGBLD_ISO_STRING_BSD_FUNCS_HEADER "cyg/libc/string/bsdstring.h"
#define CYGINT_ISO_STRING_MEMFUNCS 1
#define CYGINT_ISO_STRING_MEMFUNCS_1
#define CYGBLD_ISO_STRING_MEMFUNCS_HEADER "cyg/libc/string/string.h"
#define CYGINT_ISO_STRING_STRFUNCS 1
#define CYGINT_ISO_STRING_STRFUNCS_1
#define CYGBLD_ISO_STRING_STRFUNCS_HEADER "cyg/libc/string/string.h"
#define CYGINT_ISO_C_TIME_TYPES 1
#define CYGINT_ISO_C_TIME_TYPES_1
#define CYGBLD_ISO_C_TIME_TYPES_HEADER "cyg/libc/time/time.h"
#define CYGINT_ISO_C_CLOCK_FUNCS 1
#define CYGINT_ISO_C_CLOCK_FUNCS_1
#define CYGBLD_ISO_C_CLOCK_FUNCS_HEADER "cyg/libc/time/time.h"
#define CYGINT_ISO_SIGNAL_NUMBERS 1
#define CYGINT_ISO_SIGNAL_NUMBERS_1
#define CYGBLD_ISO_SIGNAL_NUMBERS_HEADER "cyg/libc/signals/signal.h"
#define CYGINT_ISO_SIGNAL_IMPL 1
#define CYGINT_ISO_SIGNAL_IMPL_1
#define CYGBLD_ISO_SIGNAL_IMPL_HEADER "cyg/libc/signals/signal.h"
#define CYGINT_POSIX_REALTIME_SIGNALS 0
#define CYGINT_POSIX_REALTIME_SIGNALS_0
#if CYGINT_POSIX_REALTIME_SIGNALS
# define _POSIX_REALTIME_SIGNALS 1
#endif
#define CYGINT_ISO_SETJMP 1
#define CYGINT_ISO_SETJMP_1
#define CYGBLD_ISO_SETJMP_HEADER "cyg/libc/setjmp/setjmp.h"
#define CYGINT_ISO_SIGSETJMP 0
#define CYGINT_ISO_SIGSETJMP_0
#define CYGINT_ISO_FCNTL 1
#define CYGINT_ISO_FCNTL_1
#define CYGINT_ISO_OPEN 1
#define CYGINT_ISO_OPEN_1
#define CYGINT_ISO_DIRENT 1
#define CYGINT_ISO_DIRENT_1
#define CYGBLD_ISO_DIRENT_HEADER "cyg/fileio/dirent.h"
#define CYGINT_ISO_PTHREADTYPES 0
#define CYGINT_ISO_PTHREADTYPES_0
#define CYGINT_ISO_PMUTEXTYPES 0
#define CYGINT_ISO_PMUTEXTYPES_0
#define CYGINT_ISO_BSDTYPES 1
#define CYGINT_ISO_BSDTYPES_1
#define CYGBLD_ISO_BSDTYPES_HEADER "sys/bsdtypes.h"
#define CYGINT_ISO_SCHED_IMPL 0
#define CYGINT_ISO_SCHED_IMPL_0
#define CYGINT_ISO_SEMAPHORES 0
#define CYGINT_ISO_SEMAPHORES_0
#if CYGINT_ISO_SEMAPHORES
# define _POSIX_SEMAPHORES 1
#endif
#define CYGINT_ISO_MQUEUE 0
#define CYGINT_ISO_MQUEUE_0
#if CYGINT_ISO_MQUEUE
# define _POSIX_MESSAGE_PASSING 1
#endif
#define CYGINT_ISO_POSIX_LIMITS 0
#define CYGINT_ISO_POSIX_LIMITS_0
#define CYGBLD_ISO_OPEN_MAX_HEADER "cyg/fileio/limits.h"
#define CYGBLD_ISO_NAME_MAX_HEADER "cyg/fileio/limits.h"
#define CYGINT_ISO_TERMIOS 1
#define CYGINT_ISO_TERMIOS_1
#define CYGINT_ISO_DLFCN 0
#define CYGINT_ISO_DLFCN_0
#define CYGINT_ISO_SELECT 1
#define CYGINT_ISO_SELECT_1
#define CYGINT_ISO_DNS 1
#define CYGBLD_ISO_DNS_HEADER "cyg/ns/dns/dns.h"
#define CYGINT_ISO_NETDB_PROTO 1
#define CYGBLD_ISO_NETDB_PROTO_HEADER "net/netdb.h"
#define CYGINT_ISO_NETDB_SERV 1
#define CYGBLD_ISO_NETDB_SERV_HEADER "net/netdb.h"

#endif
