#ifndef CYGONCE_PKGCONF_LIBC_SIGNALS_H
#define CYGONCE_PKGCONF_LIBC_SIGNALS_H
/*
 * File <pkgconf/libc_signals.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGSEM_LIBC_SIGNALS_THREAD_SAFE 1
#define CYGPKG_LIBC_SIGNALS_INLINE 1
#define CYGIMP_LIBC_SIGNALS_RAISE_INLINE 1
#define CYGIMP_LIBC_SIGNALS_SIGNAL_INLINE 1
#define CYGPKG_LIBC_SIGNALS_ERROR_HANDLING 1
#define CYGSEM_LIBC_SIGNALS_RAISE_SETS_ERRNO 1
#define CYGSEM_LIBC_SIGNALS_SIGNAL_SETS_ERRNO 1
#define CYGPKG_LIBC_SIGNALS_TRACING 1
#define CYGNUM_LIBC_SIGNALS_RAISE_TRACE_LEVEL 0
#define CYGNUM_LIBC_SIGNALS_RAISE_TRACE_LEVEL_0
#define CYGNUM_LIBC_SIGNALS_HWHANDLER_TRACE_LEVEL 0
#define CYGNUM_LIBC_SIGNALS_HWHANDLER_TRACE_LEVEL_0

#endif
