#ifndef CYGONCE_PKGCONF_LIBC_TIME_H
#define CYGONCE_PKGCONF_LIBC_TIME_H
/*
 * File <pkgconf/libc_time.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGSEM_LIBC_TIME_CLOCK_WORKING 1
#define CYGSEM_LIBC_TIME_TIME_WORKING 1
#define CYGSEM_LIBC_TIME_SETTIME_WORKING 1
#define CYGFUN_LIBC_TIME_POSIX 1
#define CYGPKG_LIBC_TIME_ZONES 1
#define CYGNUM_LIBC_TIME_DST_DEFAULT_STATE -1
#define CYGNUM_LIBC_TIME_STD_DEFAULT_OFFSET 0
#define CYGNUM_LIBC_TIME_STD_DEFAULT_OFFSET_0
#define CYGNUM_LIBC_TIME_DST_DEFAULT_OFFSET 3600
#define CYGNUM_LIBC_TIME_DST_DEFAULT_OFFSET_3600
#define CYGPKG_LIBC_TIME_INLINES 1
#define CYGIMP_LIBC_TIME_ASCTIME_INLINE 1
#define CYGIMP_LIBC_TIME_CTIME_INLINE 1
#define CYGIMP_LIBC_TIME_DIFFTIME_INLINE 1
#define CYGIMP_LIBC_TIME_GMTIME_INLINE 1
#define CYGIMP_LIBC_TIME_LOCALTIME_INLINE 1
#define CYGIMP_LIBC_TIME_MKTIME_INLINE 1
#define CYGIMP_LIBC_TIME_ASCTIME_R_INLINE 1
#define CYGIMP_LIBC_TIME_CTIME_R_INLINE 1
#define CYGIMP_LIBC_TIME_GMTIME_R_INLINE 1
#define CYGIMP_LIBC_TIME_LOCALTIME_R_INLINE 1
#define CYGNUM_LIBC_TIME_CLOCK_TRACE_LEVEL 0
#define CYGNUM_LIBC_TIME_CLOCK_TRACE_LEVEL_0

#endif
