#ifndef CYGONCE_PKGCONF_MEMALLOC_H
#define CYGONCE_PKGCONF_MEMALLOC_H
/*
 * File <pkgconf/memalloc.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGSEM_MEMALLOC_ALLOCATOR_FIXED_THREADAWARE 1
#define CYGSEM_MEMALLOC_ALLOCATOR_VARIABLE_THREADAWARE 1
#define CYGSEM_MEMALLOC_ALLOCATOR_VARIABLE_COALESCE 1
#define CYGPKG_MEMALLOC_ALLOCATOR_DLMALLOC 1
#define CYGIMP_MEMALLOC_ALLOCATOR_DLMALLOC_THREADAWARE 1
#define CYGIMP_MEMALLOC_ALLOCATOR_DLMALLOC_SAFE_MULTIPLE 1
#define CYGIMP_MEMALLOC_ALLOCATOR_DLMALLOC_USE_MEMCPY 1
#define CYGSEM_MEMALLOC_ALLOCATOR_SEPMETA_THREADAWARE 1
#define CYGFUN_MEMALLOC_KAPI 1
#define CYGSEM_MEMALLOC_MALLOC_ZERO_RETURNS_NULL 1
#define CYGPKG_MEMALLOC_MALLOC_ALLOCATORS 1
#define CYGBLD_MEMALLOC_MALLOC_IMPLEMENTATION_HEADER "cyg/memalloc/dlmalloc.hxx"
#define CYGIMP_MEMALLOC_MALLOC_DLMALLOC 1
#define CYGNUM_MEMALLOC_FALLBACK_MALLOC_POOL_SIZE 16384
#define CYGNUM_MEMALLOC_FALLBACK_MALLOC_POOL_SIZE_16384

#endif
