#ifndef CYGONCE_PKGCONF_PPP_H
#define CYGONCE_PKGCONF_PPP_H
/*
 * File <pkgconf/ppp.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */


#define CYGNUM_PPP_PPPD_THREAD_PRIORITY 7
#define CYGNUM_PPP_PPPD_THREAD_PRIORITY_16
#define CYGPKG_PPP_DEBUG_WARN_ONLY 1
#define CYGPKG_PPP_AUTH_DEFAULT_USER "eCos"
#define CYGPKG_PPP_AUTH_DEFAULT_PASSWD "secret"
#define CYGPKG_PPP_DEFAULT_DIALUP_NUMBER "5551234"
#define CYGPKG_PPP_PAP 1
#define CYGPKG_PPP_CHAP 1
#define CYGPKG_PPP_CHAT 1
#define CYGNUM_PPP_CHAT_ABORTS_MAX 10
#define CYGNUM_PPP_CHAT_ABORTS_MAX_10
#define CYGNUM_PPP_CHAT_ABORTS_SIZE 20
#define CYGNUM_PPP_CHAT_ABORTS_SIZE_20
#define CYGNUM_PPP_CHAT_STRING_LENGTH 256
#define CYGNUM_PPP_CHAT_STRING_LENGTH_256
#define CYGOPT_PPP_NS_NEGOTIATE 1
#define CYGOPT_PPP_DNS_CONFIGURE 1
#define CYGPKG_PPP_TEST_DEVICE "/dev/ser0"
#define CYGPKG_PPP_TESTS_AUTOMATE 1
#define CYGDAT_PPP_TEST_BAUD_RATES CYGNUM_SERIAL_BAUD_19200,CYGNUM_SERIAL_BAUD_38400,CYGNUM_SERIAL_BAUD_57600,CYGNUM_SERIAL_BAUD_115200

#endif
