#ifndef CYGONCE_PKGCONF_SYSTEM_H
#define CYGONCE_PKGCONF_SYSTEM_H
/*
 * File <pkgconf/system.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGNUM_VERSION_CURRENT 0x7fffff00
#define CYGPKG_HAL v2_0
#define CYGPKG_HAL_v2_0
#define CYGNUM_HAL_VERSION_MAJOR 2
#define CYGNUM_HAL_VERSION_MINOR 0
#define CYGNUM_HAL_VERSION_RELEASE -1
#define CYGPKG_IO v2_0
#define CYGPKG_IO_v2_0
#define CYGNUM_IO_VERSION_MAJOR 2
#define CYGNUM_IO_VERSION_MINOR 0
#define CYGNUM_IO_VERSION_RELEASE -1
#define CYGPKG_IO_SERIAL v2_0
#define CYGPKG_IO_SERIAL_v2_0
#define CYGNUM_IO_SERIAL_VERSION_MAJOR 2
#define CYGNUM_IO_SERIAL_VERSION_MINOR 0
#define CYGNUM_IO_SERIAL_VERSION_RELEASE -1
#define CYGPKG_INFRA v2_0
#define CYGPKG_INFRA_v2_0
#define CYGNUM_INFRA_VERSION_MAJOR 2
#define CYGNUM_INFRA_VERSION_MINOR 0
#define CYGNUM_INFRA_VERSION_RELEASE -1
#define CYGPKG_KERNEL v2_0
#define CYGPKG_KERNEL_v2_0
#define CYGNUM_KERNEL_VERSION_MAJOR 2
#define CYGNUM_KERNEL_VERSION_MINOR 0
#define CYGNUM_KERNEL_VERSION_RELEASE -1
#define CYGPKG_MEMALLOC v2_0
#define CYGPKG_MEMALLOC_v2_0
#define CYGNUM_MEMALLOC_VERSION_MAJOR 2
#define CYGNUM_MEMALLOC_VERSION_MINOR 0
#define CYGNUM_MEMALLOC_VERSION_RELEASE -1
#define CYGPKG_ISOINFRA v2_0
#define CYGPKG_ISOINFRA_v2_0
#define CYGNUM_ISOINFRA_VERSION_MAJOR 2
#define CYGNUM_ISOINFRA_VERSION_MINOR 0
#define CYGNUM_ISOINFRA_VERSION_RELEASE -1
#define CYGPKG_LIBC v2_0
#define CYGPKG_LIBC_v2_0
#define CYGNUM_LIBC_VERSION_MAJOR 2
#define CYGNUM_LIBC_VERSION_MINOR 0
#define CYGNUM_LIBC_VERSION_RELEASE -1
#define CYGPKG_LIBC_I18N v2_0
#define CYGPKG_LIBC_I18N_v2_0
#define CYGNUM_LIBC_I18N_VERSION_MAJOR 2
#define CYGNUM_LIBC_I18N_VERSION_MINOR 0
#define CYGNUM_LIBC_I18N_VERSION_RELEASE -1
#define CYGPKG_LIBC_SETJMP v2_0
#define CYGPKG_LIBC_SETJMP_v2_0
#define CYGNUM_LIBC_SETJMP_VERSION_MAJOR 2
#define CYGNUM_LIBC_SETJMP_VERSION_MINOR 0
#define CYGNUM_LIBC_SETJMP_VERSION_RELEASE -1
#define CYGPKG_LIBC_SIGNALS v2_0
#define CYGPKG_LIBC_SIGNALS_v2_0
#define CYGNUM_LIBC_SIGNALS_VERSION_MAJOR 2
#define CYGNUM_LIBC_SIGNALS_VERSION_MINOR 0
#define CYGNUM_LIBC_SIGNALS_VERSION_RELEASE -1
#define CYGPKG_LIBC_STARTUP v2_0
#define CYGPKG_LIBC_STARTUP_v2_0
#define CYGNUM_LIBC_STARTUP_VERSION_MAJOR 2
#define CYGNUM_LIBC_STARTUP_VERSION_MINOR 0
#define CYGNUM_LIBC_STARTUP_VERSION_RELEASE -1
#define CYGPKG_LIBC_STDIO v2_0
#define CYGPKG_LIBC_STDIO_v2_0
#define CYGNUM_LIBC_STDIO_VERSION_MAJOR 2
#define CYGNUM_LIBC_STDIO_VERSION_MINOR 0
#define CYGNUM_LIBC_STDIO_VERSION_RELEASE -1
#define CYGPKG_LIBC_STDLIB v2_0
#define CYGPKG_LIBC_STDLIB_v2_0
#define CYGNUM_LIBC_STDLIB_VERSION_MAJOR 2
#define CYGNUM_LIBC_STDLIB_VERSION_MINOR 0
#define CYGNUM_LIBC_STDLIB_VERSION_RELEASE -1
#define CYGPKG_LIBC_STRING v2_0
#define CYGPKG_LIBC_STRING_v2_0
#define CYGNUM_LIBC_STRING_VERSION_MAJOR 2
#define CYGNUM_LIBC_STRING_VERSION_MINOR 0
#define CYGNUM_LIBC_STRING_VERSION_RELEASE -1
#define CYGPKG_LIBC_TIME v2_0
#define CYGPKG_LIBC_TIME_v2_0
#define CYGNUM_LIBC_TIME_VERSION_MAJOR 2
#define CYGNUM_LIBC_TIME_VERSION_MINOR 0
#define CYGNUM_LIBC_TIME_VERSION_RELEASE -1
#define CYGPKG_LIBM v2_0
#define CYGPKG_LIBM_v2_0
#define CYGNUM_LIBM_VERSION_MAJOR 2
#define CYGNUM_LIBM_VERSION_MINOR 0
#define CYGNUM_LIBM_VERSION_RELEASE -1
#define CYGPKG_IO_WALLCLOCK v2_0
#define CYGPKG_IO_WALLCLOCK_v2_0
#define CYGNUM_IO_WALLCLOCK_VERSION_MAJOR 2
#define CYGNUM_IO_WALLCLOCK_VERSION_MINOR 0
#define CYGNUM_IO_WALLCLOCK_VERSION_RELEASE -1
#define CYGPKG_ERROR v2_0
#define CYGPKG_ERROR_v2_0
#define CYGNUM_ERROR_VERSION_MAJOR 2
#define CYGNUM_ERROR_VERSION_MINOR 0
#define CYGNUM_ERROR_VERSION_RELEASE -1
#define CYGPKG_HAL_ARM v2_0
#define CYGPKG_HAL_ARM_v2_0
#define CYGNUM_HAL_ARM_VERSION_MAJOR 2
#define CYGNUM_HAL_ARM_VERSION_MINOR 0
#define CYGNUM_HAL_ARM_VERSION_RELEASE -1
#define CYGPKG_HAL_ARM_W90N740 v2_0
#define CYGPKG_HAL_ARM_W90N740_v2_0
#define CYGNUM_HAL_ARM_W90N740_VERSION_MAJOR 2
#define CYGNUM_HAL_ARM_W90N740_VERSION_MINOR 0
#define CYGNUM_HAL_ARM_W90N740_VERSION_RELEASE -1
#define CYGBLD_HAL_TARGET_H   "pkgconf/hal_arm.h"
#define CYG_HAL_STARTUP RAM
#define CYG_HAL_STARTUP_RAM

#ifndef RW99702
#define CYG_HAL_CPUTYPE W90N740
#define CYG_HAL_CPUTYPE_W90N740
#define CYGNUM_HAL_CPUCLOCK 15000000
#define CYGNUM_HAL_CPUCLOCK_15000000
#define CYGHWR_MEMORY_LAYOUT_LDI "pkgconf/mlt_arm_w90n740_ram.ldi"
#define CYGHWR_MEMORY_LAYOUT_H "pkgconf/mlt_arm_w90n740_ram.h"
#define CYGPKG_IO_SERIAL_ARM_W90N740 v2_0
#define CYGPKG_IO_SERIAL_ARM_W90N740_v2_0
#define CYGNUM_IO_SERIAL_ARM_W90N740_VERSION_MAJOR 2
#define CYGNUM_IO_SERIAL_ARM_W90N740_VERSION_MINOR 0
#define CYGNUM_IO_SERIAL_ARM_W90N740_VERSION_RELEASE -1
/***** serial driver proc output start *****/
#define CYGDAT_IO_SERIAL_DEVICE_HEADER "pkgconf/io_serial_arm_w90n740.h"
#define CYGBLD_HAL_PLATFORM_H "pkgconf/hal_arm_w90n740.h"
#else
#define CYG_HAL_CPUTYPE W99702
#define CYG_HAL_CPUTYPE_W99702
#define CYGNUM_HAL_CPUCLOCK 12000000
#define CYGNUM_HAL_CPUCLOCK_12000000
#define CYGHWR_MEMORY_LAYOUT_LDI "pkgconf/mlt_arm_w99702_ram.ldi"
#define CYGHWR_MEMORY_LAYOUT_H "pkgconf/mlt_arm_w99702_ram.h"
#define CYGPKG_IO_SERIAL_ARM_W99702 v2_0
#define CYGPKG_IO_SERIAL_ARM_W99702_v2_0
#define CYGNUM_IO_SERIAL_ARM_W99702_VERSION_MAJOR 2
#define CYGNUM_IO_SERIAL_ARM_W99702_VERSION_MINOR 0
#define CYGNUM_IO_SERIAL_ARM_W99702_VERSION_RELEASE -1
/***** serial driver proc output start *****/
#define CYGDAT_IO_SERIAL_DEVICE_HEADER "pkgconf/io_serial_arm_w99702.h"
#define CYGBLD_HAL_PLATFORM_H "pkgconf/hal_arm_w99702.h"
#endif

#define CYGPKG_IO_FILEIO v2_0
#define CYGPKG_IO_FILEIO_v2_0
#define CYGNUM_IO_FILEIO_VERSION_MAJOR 2
#define CYGNUM_IO_FILEIO_VERSION_MINOR 0
#define CYGNUM_IO_FILEIO_VERSION_RELEASE -1
#define CYGPKG_FS_FAT v2_0
#define CYGPKG_FS_FAT_v2_0
#define CYGNUM_FS_FAT_VERSION_MAJOR 2
#define CYGNUM_FS_FAT_VERSION_MINOR 0
#define CYGNUM_FS_FAT_VERSION_RELEASE -1
#define CYGPKG_FS_RAM v2_0
#define CYGPKG_FS_RAM_v2_0
#define CYGNUM_FS_RAM_VERSION_MAJOR 2
#define CYGNUM_FS_RAM_VERSION_MINOR 0
#define CYGNUM_FS_RAM_VERSION_RELEASE -1
#define CYGPKG_FS_ROM v2_0
#define CYGPKG_FS_ROM_v2_0
#define CYGNUM_FS_ROM_VERSION_MAJOR 2
#define CYGNUM_FS_ROM_VERSION_MINOR 0
#define CYGNUM_FS_ROM_VERSION_RELEASE -1
#define CYGPKG_CRC v2_0
#define CYGPKG_CRC_v2_0
#define CYGNUM_CRC_VERSION_MAJOR 2
#define CYGNUM_CRC_VERSION_MINOR 0
#define CYGNUM_CRC_VERSION_RELEASE -1
#define CYGPKG_LINUX_COMPAT v2_0
#define CYGPKG_LINUX_COMPAT_v2_0
#define CYGNUM_LINUX_COMPAT_VERSION_MAJOR 2
#define CYGNUM_LINUX_COMPAT_VERSION_MINOR 0
#define CYGNUM_LINUX_COMPAT_VERSION_RELEASE -1
#define CYGPKG_COMPRESS_ZLIB v2_0
#define CYGPKG_COMPRESS_ZLIB_v2_0
#define CYGNUM_COMPRESS_ZLIB_VERSION_MAJOR 2
#define CYGNUM_COMPRESS_ZLIB_VERSION_MINOR 0
#define CYGNUM_COMPRESS_ZLIB_VERSION_RELEASE -1
#define CYGPKG_IO_ETH_DRIVERS v2_0
#define CYGPKG_IO_ETH_DRIVERS_v2_0
#define CYGNUM_IO_ETH_DRIVERS_VERSION_MAJOR 2
#define CYGNUM_IO_ETH_DRIVERS_VERSION_MINOR 0
#define CYGNUM_IO_ETH_DRIVERS_VERSION_RELEASE -1
#define CYGPKG_DEVS_ETH_ARM_W90N740 v2_0
#define CYGPKG_DEVS_ETH_ARM_W90N740_v2_0
#define CYGNUM_DEVS_ETH_ARM_W90N740_VERSION_MAJOR 2
#define CYGNUM_DEVS_ETH_ARM_W90N740_VERSION_MINOR 0
#define CYGNUM_DEVS_ETH_ARM_W90N740_VERSION_RELEASE -1
#define CYGPKG_NET_OPENBSD_STACK v2_0
#define CYGPKG_NET_OPENBSD_STACK_v2_0
#define CYGNUM_NET_OPENBSD_STACK_VERSION_MAJOR 2
#define CYGNUM_NET_OPENBSD_STACK_VERSION_MINOR 0
#define CYGNUM_NET_OPENBSD_STACK_VERSION_RELEASE -1
/***** Networking stack proc output start *****/
#define CYGDAT_NET_STACK_CFG "pkgconf/net_openbsd_stack.h"
/***** Networking stack proc output end *****/
#define CYGPKG_NET v2_0
#define CYGPKG_NET_v2_0
#define CYGNUM_NET_VERSION_MAJOR 2
#define CYGNUM_NET_VERSION_MINOR 0
#define CYGNUM_NET_VERSION_RELEASE -1
#define CYGPKG_NS_DNS v2_0
#define CYGPKG_NS_DNS_v2_0
#define CYGNUM_NS_DNS_VERSION_MAJOR 2
#define CYGNUM_NS_DNS_VERSION_MINOR 0
#define CYGNUM_NS_DNS_VERSION_RELEASE -1
//#define CYGPKG_HTTPD v2_0
//#define CYGPKG_HTTPD_v2_0
//#define CYGNUM_HTTPD_VERSION_MAJOR 2
//#define CYGNUM_HTTPD_VERSION_MINOR 0
//#define CYGNUM_HTTPD_VERSION_RELEASE -1
//#define CYGPKG_NET_BLUEZ_STACK v2_0
#define CYGPKG_NET_BLUEZ_STACK_v2_0
#define CYGNUM_NET_BLUEZ_STACK_VERSION_MAJOR 2
#define CYGNUM_NET_BLUEZ_STACK_VERSION_MINOR 0
#define CYGNUM_NET_BLUEZ_STACK_VERSION_RELEASE -1
#define CYGPKG_IO_W99685 v2_0
#define CYGPKG_IO_W99685_v2_0
#define CYGNUM_IO_W99685_VERSION_MAJOR 2
#define CYGNUM_IO_W99685_VERSION_MINOR 0
#define CYGNUM_IO_W99685_VERSION_RELEASE -1
#define CYGPKG_DEVS_MEDIA_VIDEO_W99685 v2_0
#define CYGPKG_DEVS_MEDIA_VIDEO_W99685_v2_0
#define CYGNUM_DEVS_MEDIA_VIDEO_W99685_VERSION_MAJOR 2
#define CYGNUM_DEVS_MEDIA_VIDEO_W99685_VERSION_MINOR 0
#define CYGNUM_DEVS_MEDIA_VIDEO_W99685_VERSION_RELEASE -1
#define CYGPKG_IO_BLUETOOTH_HCI v2_0
#define CYGPKG_IO_BLUETOOTH_HCI_v2_0
#define CYGNUM_IO_BLUETOOTH_HCI_VERSION_MAJOR 2
#define CYGNUM_IO_BLUETOOTH_HCI_VERSION_MINOR 0
#define CYGNUM_IO_BLUETOOTH_HCI_VERSION_RELEASE -1

#define CYGPKG_DEVS_SDRAM v2_0
#define CYGPKG_DEVS_SDRAM_v2_0
#define CYGNUM_DEVS_SDRAM_VERSION_MAJOR 2
#define CYGNUM_DEVS_SDRAM_VERSION_MINOR 0
#define CYGNUM_DEVS_SDRAM_VERSION_RELEASE -1
#define CYGPKG_IO_SDRAM v2_0
#define CYGPKG_IO_SDRAM_v2_0
#define CYGNUM_IO_SDRAM_VERSION_MAJOR 2
#define CYGNUM_IO_SDRAM_VERSION_MINOR 0
#define CYGNUM_IO_SDRAM_VERSION_RELEASE -1

#endif